environment:
  matrix:
    # - nodejs_version: "10"
    #   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
    - nodejs_version: "8"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GYP_MSVS_VERSION: "2015"
    - nodejs_version: "10"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GYP_MSVS_VERSION: "2015"
    - nodejs_version: "12"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GYP_MSVS_VERSION: "2017"
    - nodejs_version: "12"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GYP_MSVS_VERSION: "2019"
    - nodejs_version: "13"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GYP_MSVS_VERSION: "2019"


install:
  - ps: if (!$isLinux) { Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) x64 }
  # - sh: sudo apt-get install python g++ make
  # - sh: nvm install $nodejs_version
  - npm install

test_script:
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - node --version
  - npm --version
  - npm test

build: off
shallow_clone: true
version: "{build}"
