branches:
  only:
    - master
    # - ci_trial
os:
  - osx
sudo: false
language: cpp
addons:
env:
  matrix:
    - TRAVIS_NODE_VERSION="8"
    - TRAVIS_NODE_VERSION="10"
    - TRAVIS_NODE_VERSION="12"

install:
  - rm -rf ~/.nvm && git clone https://github.com/nvm-sh/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - $CXX --version
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Install dependencies and build
  - npm run ci:install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm install jest --save-dev
  - npm test